#!/bin/sh

dir="images/ubuntu"
release_number=22.04
name="ubuntu-base-22.04-base-arm64.tar.gz"
color='\033[0;92m'
no_color='\033[0m'

echo $color"==> Getting Ubuntu 22.04.2 Jammy Jellyfish""${no_color}"
wget https://cdimage.ubuntu.com/ubuntu-base/releases/$release_number/release/$name

mkdir -p $dir

tar xf $name --directory=$dir
rm $name

echo $color"==> Preparing network...""${no_color}"
sudo cp -b /etc/resolv.conf $dir/etc/resolv.conf
sudo cp /usr/bin/qemu-aarch64-static $dir/usr/bin/
sudo cp /bin/qemu-aarch64-static $dir/bin/
echo $color"==> Done.""${no_color}"
